services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    staticPublishPath: public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:rx57YA75Fjs9vtWM52mrNuK8cc7d2SJvUNHfAr9WsjM=
      - key: APP_DEBUG
        value: false
      - key: APP_URL 
        value: https://shsi-svpf.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-ct25qpd6l47c73bkhamg-a.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: shsi
      - key: DB_USERNAME
        value: shsi_user
      - key: DB_PASSWORD
        value: 7aS6IV4SHVtLzIfTgTDfKS84ArZbBJt1
